# Used in theme
baseURL = "https://tranquility.one"
copyright = "2019–2020"
keywords = "Tranquility, Minecraft"
languageCode = 'en-us'
theme = 'hugo-base'
title = 'Tranquility'

# Other options
enableGitInfo = true
pluralizeListTitles = false
rssLimit = 32

[author]
	name = 'StickFig'
	email = 'admin@tranquility.one'

[frontmatter]
	date = [':filename', ':default']
	publishDate = [':filename', ':default']

[markup.goldmark.renderer]
	unsafe = true

[menu]
	[[menu.main]]
		identifier = 'discord'
		name= '&#xf392; Discord'
		url = '/discord'
	[[menu.main]]
		identifier = 'map'
		name= '&#xf279 Map'
		url = '/map'

[params]
	authorMail = 'admin@tranquility.one'
	backgroundImage = 'images/bg.jpg'
	css = 'css/style.css'
	description = "The Tranquility Minecraft server"
	iconPNG = 'images/logo.png'
	iconSVG = 'images/favicon.svg'
	logo = "images/logo.png"
	repo = "https://github.com/tranquility-one/tranquility.one"
