# Used in theme
baseURL = "https://tranquility.one"
copyright = "2019"
keywords = "Tranquility, Minecraft"
languageCode = 'en-us'
theme = 'hmvt'
title = 'Tranquility'

# Other options
enableGitInfo = true
pluralizeListTitles = false
rssLimit = 32

[author]
	name = 'StickFig'
	email = 'admin@tranquility.one'

[markup.goldmark.renderer]
	unsafe = true

[menu]
	[[menu.main]]
		identifier = 'discord'
		name= 'Discord'
		url = '/discord'
	[[menu.main]]
		identifier = 'model'
		name= '3D World'
		url = '/3d'
	[[menu.main]]
		identifier = 'map'
		name= 'Map'
		url = '/map'

[params]
	background = '/images/bg.jpg'
	description = "The Tranquility Minecraft server"
	iconPNG = 'images/logo.png'
	iconSVG = 'images/favicon.svg'
	logo = "images/logo.png"
	repo = "https://github.com/tranquility-one/tranquility.one"
