title = "Tranquility"
baseURL = "https://tranquility.one"

disableHugoGeneratorInject = true
theme = "hugo-stma"

[params]
	author = "stick at stma dot is"
	color = "#07076f"
	custom_css = ["style.css"]
	description = "Links and information regarding the Tranquility server"
	keywords = "Tranquility, Minecraft"
	logo = "logo.png"
	repo_addr = "https://gitlab.com/nstickney/tranquility.one"
	repo_text = "GitLab"
