title = "Tranquility"
baseURL = "https://tranquility.one"

disableHugoGeneratorInject = true
theme = "hugo-stma"

[params]
	author = "StickFig"
	custom_css = ["style.css"]
	copyright = "2019"
	description = "Links and information regarding the Tranquility server"
	keywords = "Tranquility, Minecraft"
