title = "hugo-bare"
baseURL = "http://example.org/"
disableHugoGeneratorInject = true
theme = "bare"

[params]
	author = "nstickney@pm.me"
	color = "#eeeeee"
	description = "Barebones Hugo site"
	keywords = "default, hugo, minimal, standard, standards, website"
