title = "Tranquility"
baseURL = "https://tranquility.one"

disableHugoGeneratorInject = true
theme = "stma"

[params]
	author = "StickFig"
	color = "#eeeeee"
	copyright = "2019"
	description = "Links and information regarding the Tranquility server"
	keywords = "Tranquility, Minecraft"
