title = "Tranquility"
baseURL = "https://tranquility.one"

disableHugoGeneratorInject = true
theme = "hugo-stma"

[params]
	author = "StickFig"
	color = "#07076f"
	custom_css = ["style.css"]
	copyright = "2019"
	description = "Links and information regarding the Tranquility server"
	keywords = "Tranquility, Minecraft"
	repo_addr = "https://gitlab.com/nstickney/tranquility.one"
	repo_text = "GitLab"
